### PR TITLE
Refactor app commands

### PR DESCRIPTION
**Pull request by stevenpkg**
Have refactored commands to now use action passed with the output

### CODE REVIEW

**Comment by stevenpkg** [comment]
this update also fixes the radio bug

**Comment by germanattanasio** [comment]
@stevenpkg travis is failing because of lint issues. Try to run:

```
npm run lint
```

And check the output

**Comment by stevenpkg** [comment]
This seems to be the problem

/Users/steve/MyFiles/IBM/projects/github/car-dashboard/ui/js/tooltip-dialogs.js
  24:1   error  Definition for rule 'react/jsx-wrap-multilines' was not found  react/jsx-wrap-multilines
  24:31  error  Missing space before function parentheses                      space-before-function-paren
  58:30  error  Missing space before function parentheses                      space-before-function-paren
  61:20  error  Missing space before function parentheses                      space-before-function-paren
  64:20  error  Missing space before function parentheses                      space-before-function-paren
  68:26  error  Missing space before function parentheses                      space-before-function-paren


Any ideas?

**Comment by stevenpkg** [comment]
I had over 3000 errors with whitespace etc, to many to fix. I noticed that .eslintignore and .eslintrc (now named .eslintrc.yml) had been changed. I changed my refactor branch to use they new setting and only got 30 or so errors. I have fixed these errors now and only left a few warning (all console)
/Users/steve/MyFiles/IBM/projects/github/car-dashboard/ui/ibm/speech-to-text.js
  90:15  warning  Unexpected console statement  no-console
  97:9   warning  Unexpected console statement  no-console

/Users/steve/MyFiles/IBM/projects/github/car-dashboard/ui/js/api.js
  80:9  warning  Unexpected console statement  no-console
  84:7  warning  Unexpected console statement  no-console

/Users/steve/MyFiles/IBM/projects/github/car-dashboard/ui/js/ui_tests/tests.js
   40:7  warning  Unexpected console statement  no-console
  100:9  warning  Unexpected console statement  no-console

✖ 6 problems (0 errors, 6 warnings)


So now there are a few merge problems?

**Comment by germanattanasio** [comment]
@stevenpkg it seems like you are using an older version. Your initial changes were in sync with the code in `master` it's just that you had some lint issues. Look at Travis: https://travis-ci.org/watson-developer-cloud/car-dashboard/builds/197105746#L312

You were using double quotes for strings.

**Comment by germanattanasio** [comment]
You need to pull the changes from `master` run `npm install` to make sure your `node_modules` is in sync with the `package.json` file and then run `npm run lint`.

Once you have only warning make sure you commit all the changes. Right now there are merge conflicts in some of the files.

**Comment by stevenpkg** [comment]
Thanks German, will do it tomorrow

**Pull request closed without merging**
