### PR TITLE
Update car_workspace.json

### PR DESCRIPTION
**Pull request by germanattanasio**
@stevenpkg, the team wants to update the `workspace.json` this PR should be tested to make sure it doesn't break anything

### CODE REVIEW

**Comment by ttlew** [comment]
This update removes some profanities, an ask from leadership from a customer for the demo.

**Review by stevenpkg — COMMENTED** [review]
Have asked @Oliver-I to comment as it really his doman

**Comment by Oliver-I** [comment]
@ttlew All examples come from end users, as I've been told before regarding the NLC/NLU component, if we modify the original text we reduce the accuracy of the system. Are we sure we want to remove profanity? End users typing profanity is inevitable and by removing it we risk making the system appear inaccurate/less intelligent.

**Comment by Oliver-I** [comment]
@ttlew This pull request can't be used as it doesn't contain the Slot example (and possibly the Fuzzy matching example). I will need to manually remove the examples.
@germanattanasio  Please do not use this pull request, a new pull request will be raised.

**Pull request closed without merging**
